set_property PACKAGE_PIN E3       [get_ports {clock}]
set_property IOSTANDARD  LVCMOS33 [get_ports {clock}]
create_clock -period 10.0         [get_ports {clock}]

set_property PACKAGE_PIN C2       [get_ports {reset}]
set_property IOSTANDARD  LVCMOS33 [get_ports {reset}]

set_property PACKAGE_PIN H5       [get_ports {io_blinkyHost_led[0]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {io_blinkyHost_led[0]}]
set_property PACKAGE_PIN J5       [get_ports {io_blinkyHost_led[1]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {io_blinkyHost_led[1]}]
set_property PACKAGE_PIN T9       [get_ports {io_blinkyHost_led[2]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {io_blinkyHost_led[2]}]
set_property PACKAGE_PIN T10      [get_ports {io_blinkyHost_led[3]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {io_blinkyHost_led[3]}]
